<script setup>
import {ref,computed,onMounted} from 'vue';import {supabase,audit} from '../lib/supabase.js'
const posts=ref([]),query=ref(''),loading=ref(true),error=ref(''),editing=ref(null),saving=ref(false),preview=ref(null)
const colors={'技术手记':'#d9e7e8','生活随笔':'#f2d7c8','成长思考':'#dfe8c7'}
const filtered=computed(()=>posts.value.filter(p=>`${p.title}${p.category}${p.excerpt}`.toLowerCase().includes(query.value.toLowerCase())))
async function load(){loading.value=true;const {data,error:e}=await supabase.from('blog_posts').select('*').order('updated_at',{ascending:false});if(e)error.value=e.message;else posts.value=data||[];loading.value=false}
function edit(row=null){editing.value=row?{...row}:{title:'',category:'技术手记',excerpt:'',content:'',status:'draft',color:colors['技术手记']}}
async function save(){if(!editing.value.title.trim()||!editing.value.content.trim()){error.value='请填写标题和正文';return}saving.value=true;const {data:{user}}=await supabase.auth.getUser();const p=editing.value;const payload={user_id:p.user_id||user.id,title:p.title.trim(),category:p.category,excerpt:p.excerpt.trim()||p.content.trim().slice(0,96),content:p.content.trim(),status:p.status,read_minutes:Math.max(1,Math.ceil(p.content.trim().length/450)),color:colors[p.category],updated_at:new Date().toISOString()};const result=p.id?await supabase.from('blog_posts').update(payload).eq('id',p.id).select().single():await supabase.from('blog_posts').insert(payload).select().single();saving.value=false;if(result.error){error.value=result.error.message;return}await audit(p.id?'blog.update':'blog.create','blog_post',result.data.id,{status:result.data.status});editing.value=null;await load()}
async function setStatus(row,status){if(status==='draft'&&!confirm('确定将这篇文章下线吗？'))return;const {error:e}=await supabase.from('blog_posts').update({status,updated_at:new Date().toISOString()}).eq('id',row.id);if(e){error.value=e.message;return}await audit(status==='published'?'blog.publish':'blog.unpublish','blog_post',row.id,{status});await load()}
async function remove(row){if(!confirm(`永久删除“${row.title}”？建议优先使用下线。`))return;const {error:e}=await supabase.from('blog_posts').delete().eq('id',row.id);if(e){error.value=e.message;return}await audit('blog.delete','blog_post',row.id,{title:row.title});await load()}
onMounted(load)
</script>
<template><div class="page"><div class="page-head"><div><h2>博客内容</h2><p>草稿、预览、发布与下线集中管理，前台只负责阅读。</p></div><button class="btn" @click="edit()">＋ 新建文章</button></div><div v-if="error" class="notice">{{error}}</div><section class="card"><div class="toolbar"><input v-model="query" placeholder="搜索标题、分类或摘要"></div><div v-if="loading" class="loading">正在读取文章…</div><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>文章</th><th>分类</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id"><td><b>{{row.title}}</b><small>{{row.excerpt}}</small></td><td>{{row.category}}</td><td><span :class="['badge',{off:row.status!=='published'}]">{{row.status==='published'?'已发布':'草稿'}}</span></td><td>{{new Date(row.updated_at).toLocaleString('zh-CN')}}</td><td><button class="btn secondary" @click="preview=row">预览</button> <button class="btn secondary" @click="edit(row)">编辑</button> <button class="btn secondary" @click="setStatus(row,row.status==='published'?'draft':'published')">{{row.status==='published'?'下线':'发布'}}</button> <button class="btn danger" @click="remove(row)">删除</button></td></tr></tbody></table><div v-if="!filtered.length" class="empty">暂无文章</div></div></section><div v-if="editing" class="modal-layer" @click.self="editing=null"><form class="modal" @submit.prevent="save"><header><h2>{{editing.id?'编辑文章':'新建文章'}}</h2><button type="button" @click="editing=null">×</button></header><div class="field"><label>标题</label><input v-model="editing.title" maxlength="120" required></div><div class="form-grid"><div class="field"><label>分类</label><select v-model="editing.category"><option v-for="c in Object.keys(colors)" :key="c">{{c}}</option></select></div><div class="field"><label>状态</label><select v-model="editing.status"><option value="draft">草稿</option><option value="published">发布</option></select></div></div><div class="field"><label>摘要</label><input v-model="editing.excerpt" maxlength="240" placeholder="留空自动生成"></div><div class="field"><label>正文</label><textarea v-model="editing.content" maxlength="50000" style="min-height:280px" required></textarea></div><footer><button type="button" class="btn secondary" @click="editing=null">取消</button><button class="btn" :disabled="saving">{{saving?'保存中…':'保存文章'}}</button></footer></form></div><div v-if="preview" class="modal-layer" @click.self="preview=null"><article class="modal"><header><h2>{{preview.title}}</h2><button @click="preview=null">×</button></header><p style="color:var(--muted)">{{preview.category}} · {{preview.read_minutes}} 分钟</p><p style="white-space:pre-wrap;line-height:1.9">{{preview.content}}</p></article></div></div></template>
